# Generated by Django 2.2 on 2022-05-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
