# Generated by Django 2.2 on 2022-06-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
