# Generated by Django 2.2 on 2022-06-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='user',
            new_name='user_agent',
        ),
    ]
