# Generated by Django 2.2 on 2022-05-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0002_auto_20220510_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='user',
        ),
    ]
