# Generated by Django 2.2 on 2022-06-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0002_auto_20220604_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='fullname',
        ),
    ]
