# Generated by Django 2.2 on 2022-05-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0002_customuser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='register_as',
            field=models.CharField(default='', max_length=100),
        ),
    ]
