# Generated by Django 2.2 on 2022-06-09 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0002_auto_20220609_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
