# Generated by Django 2.2 on 2022-06-09 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0003_auto_20220609_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='feature',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='feature_count', to='real.Featured'),
            preserve_default=False,
        ),
    ]
