# Generated by Django 2.2 on 2022-05-20 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0003_remove_listing_photo_6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/photos'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/photos'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/photos'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='images/photos'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='images/photos'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.CharField(max_length=225),
        ),
        migrations.CreateModel(
            name='Bookmarklisting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('property', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='real.Listing')),
                ('users', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
