# Generated by Django 2.2 on 2022-06-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0004_auto_20220604_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='description',
            new_name='des',
        ),
    ]
