# Generated by Django 2.2 on 2022-06-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0005_auto_20220609_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_count', to='real.Featured'),
        ),
    ]
