# Generated by Django 2.2 on 2022-06-06 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0005_auto_20220604_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('property_type', models.CharField(max_length=225)),
                ('price', models.FloatField()),
                ('area', models.CharField(max_length=225)),
                ('bedrooms', models.CharField(max_length=225)),
                ('bathrooms', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('building_Age', models.CharField(blank=True, max_length=225, null=True)),
                ('garage', models.CharField(blank=True, default=0, max_length=225, null=True)),
                ('Rooms', models.CharField(blank=True, max_length=225, null=True)),
                ('sqft', models.CharField(max_length=225)),
                ('image', models.FileField(upload_to='images/photos')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='images/photos')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='images/photos')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='images/photos')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=225)),
                ('contact_phone', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, default='', null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='des',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.FileField(upload_to='images/photos'),
        ),
    ]
