# Generated by Django 2.2 on 2022-05-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0006_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.FileField(default='avatar.png', upload_to='images/profile_img'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.FileField(default='images/', upload_to=''),
        ),
    ]
