# Generated by Django 2.2 on 2022-06-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0006_auto_20220611_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured',
            name='feature',
        ),
    ]
