# Generated by Django 2.2 on 2022-06-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0006_auto_20220606_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featured',
            old_name='is_published',
            new_name='is_active',
        ),
    ]
