# Generated by Django 2.2 on 2022-06-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0008_auto_20220607_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featured',
            old_name='address',
            new_name='location',
        ),
    ]
