# Generated by Django 2.2 on 2022-06-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0008_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
