# Generated by Django 2.2 on 2022-06-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0009_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
