# Generated by Django 2.2 on 2022-06-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0010_agent_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='contact_phone',
        ),
    ]
