# Generated by Django 2.2 on 2022-06-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0011_auto_20220607_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='message',
        ),
        migrations.AddField(
            model_name='review',
            name='property_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
